name: Build
on: workflow_dispatch

jobs:
  packager:
    name: Package and Upload
    runs-on: ubuntu-latest
    steps:
      - name: Install SVN
        run: sudo apt install -y subversion

      - name: Checkout
        uses: actions/checkout@v6

      - name: Bigwigs packager
        uses: BigWigsMods/packager@master
        with:
          args: "-o -u -m .pkgmeta"

      - name: Print some stuff
        run: ls -la .release

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: .release/CoreLootManager*.zip